remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: solitary's memos
description: "solitary"
markdown: kramdown
categories: [post]
defaults:
  -
    scope:
      path: post
    values:
      layout: post
      mathjax: true
      category: post
