remote_theme: DottleWither/cayman
title: solitary's memos
description: "solitary"
markdown: kramdown
categories: [post]
defaults:
  -
    scope:
      path: post
    values:
      layout: post
      mathjax: true
      category: post
